apiVersion: v1
kind: Service
metadata:
  name: k3s-simple-website
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: k3s-simple-website
